apiVersion: garden.io/v1
kind: Project
name: rust-example
variables:
  base-hostname: rust.local.demo.garden

environments:
  - name: dev
  - name: release
providers:
  - name: local-kubernetes
